# Generated by Django 4.2.4 on 2023-08-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_rename_first_name_usuario_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivel',
            name='link_dashboard',
            field=models.URLField(blank=True),
        ),
    ]
