# Generated by Django 4.2.4 on 2023-08-21 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0007_remove_userprofile_nivel_alter_usuario_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='nivel',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nivel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Dashboard.nivel'),
        ),
    ]
