# Generated by Django 4.2.4 on 2023-08-21 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0008_remove_customuser_nivel_userprofile_nivel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
