# Generated by Django 4.2.4 on 2023-08-22 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Dashboard', '0013_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nivel',
            new_name='DashboardLink',
        ),
        migrations.AlterModelOptions(
            name='dashboardlink',
            options={'verbose_name': 'Link Dashboard', 'verbose_name_plural': 'Links Dashboards'},
        ),
    ]
