# Generated by Django 4.2.4 on 2023-08-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0014_rename_nivel_dashboardlink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardlink',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
