# Generated by Django 4.2.4 on 2023-08-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0015_dashboardlink_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardlink',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
