# Generated by Django 4.2.4 on 2023-08-22 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Dashboard', '0016_dashboardlink_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardlink',
            name='nome_relatorio',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dashboardlink',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name='Contratante'),
        ),
    ]
