# Generated by Django 4.2.4 on 2023-08-25 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0018_alter_dashboardlink_ativo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardlink',
            options={'permissions': [('pode_editar_relatorio', 'Pode editar relatórios'), ('pode_criar_relatorio', 'Pode criar relatórios')], 'verbose_name': 'Link Dashboard', 'verbose_name_plural': 'Links Dashboards'},
        ),
    ]
