# Generated by Django 4.2.4 on 2024-04-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0020_alter_dashboardlink_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardlink',
            name='cod_cliente',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
